{
 "title": "Ballerina Metrics",
 "description": "Monitor Ballerina HTTP/HTTPs Services, GraphQL Services, HTTP Clients, and SQL Clients",
 "tags": [
  "ballerina",
  "http",
  "sql"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(requests_total_value, instance)"
   },
   {
    "name": "entrypoint_function_module",
    "label": "entrypoint-function-module",
    "query": "label_values(requests_total_value, entrypoint_function_module)"
   },
   {
    "name": "entrypoint_function_position",
    "label": "entrypoint-function-position",
    "query": "label_values(requests_total_value, entrypoint_function_position)"
   },
   {
    "name": "protocol",
    "label": "protocol",
    "query": "label_values(requests_total_value, protocol)"
   },
   {
    "name": "http_method",
    "label": "http-method",
    "query": "label_values(requests_total_value, http_method)"
   },
   {
    "name": "http_url",
    "label": "http-url",
    "query": "label_values(requests_total_value, http_url)"
   },
   {
    "name": "src_object_name",
    "label": "src-object-name",
    "query": "label_values(requests_total_value, src_object_name)"
   },
   {
    "name": "src_function_name",
    "label": "src-function-name",
    "query": "label_values(requests_total_value, src_function_name)"
   },
   {
    "name": "db_action",
    "label": "db-action",
    "query": "label_values(requests_total_value{src_object_name=\"ballerinax/mysql/Client\"}, src_function_name)"
   },
   {
    "name": "http_status_code_group",
    "label": "http-status-code-group",
    "query": "label_values(requests_total_value, http_status_code_group)"
   },
   { "name": "peer_address", "label": "peer-address", "query": "label_values(peer_address)" },
   {
    "name": "src_resource_accessor",
    "label": "src_resource_accessor",
    "query": {
     "query": "label_values(src_resource_accessor)"
    }
   },
   {
    "name": "graphql_service_operation_name",
    "label": "graphql-service-operation-name",
    "query": {
     "query": "label_values(graphql_service_operation_name)"
    }
   },
   {
    "name": "graphql_service_operation_type",
    "label": "graphql_service_operation_type",
    "query": {
     "query": "label_values(graphql_service_operation_type)"
    }
   },
   {
    "name": "graphql_service_errors",
    "label": "graphql_service_errors",
    "query": {
     "query": "label_values(graphql_service_errors)"
    }
   },
   {
    "name": "graphql_service_field_name",
    "label": "graphql_service_field_name",
    "query": {
     "query": "label_values(graphql_service_field_name)"
    }
   },
   {
    "name": "entrypoint_service_name",
    "label": "entrypoint_service_name",
    "query": {
     "query": "label_values(entrypoint_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ballerina Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ballerina HTTP Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests / min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max_over_time(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=~\"$src_object_name\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=~\"$src_object_name\"}[1m]))"
      }
     ]
    },
    {
     "title": "Errors /  min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m]))) OR vector(0))+((sum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m]))) OR vector(0))"
      }
     ]
    },
    {
     "title": "Inprogress Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(inprogress_requests_value{instance=~\"$instance\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=~\"$src_object_name\"})"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}) OR vector(0))\n+\n(sum(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}) OR vector(0)))\n*100\n/\nsum(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\"})\n"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops", "label": "Requests / sec" }
     ],
     "targets": [
      {
       "expr": "sum without (http_status_code_group)(rate(requests_total_value{instance=~\"$instance\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=\"ballerina/http/Caller\"}[1m]))",
       "legendFormat": "Instance: {{instance}}, Source Object Name: {{src_object_name}}, Source Function Name: {{src_function_name}}"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "expr": "response_time_seconds{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\"}",
       "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}, Quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "HTTP Status Codes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Requests / sec" }
     ],
     "targets": [
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"1xx\"}[1m])",
       "legendFormat": "1xx Informational responses - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"2xx\"}[1m])",
       "legendFormat": "2xx Successful responses - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"3xx\"}[1m])",
       "legendFormat": "3xx Redirections - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])",
       "legendFormat": "4xx Client errors - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])",
       "legendFormat": "5xx Server errors - Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Top 5 services",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,requests_total_value{src_service_resource=\"true\"})",
       "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina HTTP Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests / min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( max_over_time(requests_total_value{src_object_name=\"ballerina/http/HttpClient\",instance=~\"$instance\", peer_address=~\"$peer_address\",src_function_name=~\"$src_function_name\"}[1m]) - min_over_time(requests_total_value{src_object_name=\"ballerina/http/HttpClient\",instance=~\"$instance\", peer_address=~\"$peer_address\",src_function_name=~\"$src_function_name\"}[1m]) )"
      }
     ]
    },
    {
     "title": "Errors /  min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum( max_over_time(requests_total_value{ instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"4xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time(requests_total_value{ instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"4xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))) OR vector(0)) + ((sum(max_over_time(requests_total_value{ instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"5xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"5xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))) OR vector(0))"
      }
     ]
    },
    {
     "title": "Inprogress Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(inprogress_requests_value{src_object_name=\"ballerina/http/HttpClient\",instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}) OR vector(0)) + (sum({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}) OR  vector(0)))*100 / sum({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\"})\n"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ops", "label": "Requests / sec" }
     ],
     "targets": [
      {
       "expr": "sum without (http_status_code_group) (rate(requests_total_value{instance=~\"$instance\",peer_address=~\"$peer_address\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))",
       "legendFormat": "Instance: {{instance}}, Method: {{http_method}}, Peer Address: {{peer_address}}, Service Name: {{entrypoint_service_name}}"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "expr": "response_time_seconds{instance=~\"$instance\",peer_address=~\"$peer_address\",src_object_name=\"ballerina/http/HttpClient\"}",
       "legendFormat": "Instance: {{instance}}, Method: {{http_method}}, Peer Address: {{peer_address}}, Service Name: {{entrypoint_service_name}}"
      }
     ]
    },
    {
     "title": "HTTP Status Codes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Requests / sec" }
     ],
     "targets": [
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"1xx\"}[1m])",
       "legendFormat": "1xx Informational responses - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"2xx\"}[1m])",
       "legendFormat": "2xx Successful responses - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"3xx\"}[1m])",
       "legendFormat": "3xx Redirections - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}[1m])",
       "legendFormat": "4xx Client errors - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}[1m])",
       "legendFormat": "5xx Server errors - Instance: {{instance}}, Peer Address: {{peer_address}}"
      }
     ]
    },
    {
     "title": "Top 5 remote services",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,requests_total_value{src_object_name=\"ballerina/http/HttpClient\"})",
       "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina SQL Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Executions / min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m]))"
      }
     ]
    },
    {
     "title": "Errors /  min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (max_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m])) OR  vector(0)"
      }
     ]
    },
    {
     "title": "Inprogress Statements",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(inprogress_requests_value{src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"})"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}) * 100 / sum(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"})"
      }
     ]
    },
    {
     "title": "Ballerina SQL Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ops", "label": "Statements / sec" }
     ],
     "targets": [
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m])",
       "legendFormat": "Instance: {{instance}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    },
    {
     "title": "Ballerina SQL Response Time Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "expr": "response_time_seconds{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}",
       "legendFormat": "Instance: {{instance}}, Quantile: {{quantile}}, Time Window: {{timeWindow}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    },
    {
     "title": "Ballerina SQL Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Statements / sec" }
     ],
     "targets": [
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m]) OR  vector(0)",
       "legendFormat": "Instance: {{instance}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    },
    {
     "title": "Top 5 SQL actions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,requests_total_value{src_function_name=~\"$src_function_name\",src_object_name=\"ballerinax/mysql/Client\"})",
       "legendFormat": "Instance: {{instance}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina GraphQL Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Requests / min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}[1m]) - min_over_time(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}[1m])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Errors /  min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( max_over_time(requests_total_value{entrypoint_service_name=\"graphql:Document\", graphql_service_errors=~\"graphql_service_execution_error|graphql_service_validation_error|graphql_service_parsing_error\"}[1m]) - min_over_time(requests_total_value{entrypoint_service_name=\"graphql:Document\", graphql_service_errors=~\"graphql_service_execution_error|graphql_service_validation_error|graphql_service_parsing_error\"}[1m])) OR vector(0)\n"
    }
   ]
  },
  {
   "title": "Inprogress Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(inprogress_requests_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(requests_total_value{entrypoint_service_name=\"graphql:Document\", graphql_service_errors=~\"graphql_service_execution_error|graphql_service_validation_error|graphql_service_parsing_error\"}) OR vector(0)) * 100 / \n(sum(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}) OR vector(100))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}) OR vector(0)",
     "legendFormat": "Entrypoint Service Name: graphql:Document"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}[1m])) OR vector(0)",
     "legendFormat": "Instance: {{instance}}, Source Object Name: {{src_object_name}}, Source Function Name: {{src_function_name}}"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "response_time_seconds{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=~\"query|mutation|subscription\"}",
     "legendFormat": "Instance: {{instance}}, Operation Type: {{src_resource_accessor}}, Quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Fields",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (graphql_service_field_name, instance) (requests_total_value{graphql_service_field_name=~\"$graphql_service_field_name\"}))",
     "legendFormat": "Instance: {{instance}}, Field Name: {{graphql_service_field_name}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=\"query\"}) OR vector(0)",
     "legendFormat": "Operation Type: query"
    },
    {
     "expr": "sum(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=\"mutation\"}) OR vector(0)",
     "legendFormat": "Operation Type: mutation"
    },
    {
     "expr": "sum(requests_total_value{entrypoint_service_name=\"graphql:Document\", entrypoint_function_name=\"execution\", src_resource_accessor=\"subscription\"}) OR vector(0)",
     "legendFormat": "Operation Type: subscription"
    }
   ]
  }
 ]
}