moderate = true

[databaseConfig]
database = "social_media_database"
user = "social_media_user"
password = "dummypassword"
host = "localhost"
port = 3306

[sentimentEndpointConfig]
endpointUrl = "http://localhost:9098/text-processing"
retryInterval = 3.0

